# 容器 配置
server:
  port: 80
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

# 数据库 及 Redis 配置    
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
  datasource:
    url: jdbc:mysql://bdm29473944.my3w.com/bdm29473944_db?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: bdm29473944
    password: Wcy123456
    sql-script-encoding: utf-8
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 10
  mail:
    host: smtp.163.com
    username: 13275025502@163.com
    password: qq123456
    properties:
      mail:
        smtp:
          auth: false
        starttls:
          enable: false
          required: false

# Mybatis 配置
mybatis:
  config-location: classpath:/mybatis.xml

# Redis Key 前缀
redis:
  prefix:
    signUp: SIGN

# 本站信息
app:
  name: 种花家
  domain: zhonghuajia.tech